# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linpredcompute <- function(X, nsites, p, beta, offset) {
    .Call(`_CARBayes_linpredcompute`, X, nsites, p, beta, offset)
}

quadform <- function(Wtriplet, Wtripletsum, n_triplet, nsites, phi, theta, rho) {
    .Call(`_CARBayes_quadform`, Wtriplet, Wtripletsum, n_triplet, nsites, phi, theta, rho)
}

binomialcarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, trials, phi_tune, rho, offset) {
    .Call(`_CARBayes_binomialcarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, trials, phi_tune, rho, offset)
}

binomialcarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, phi_tune, rho, offset) {
    .Call(`_CARBayes_binomialcarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, phi_tune, rho, offset)
}

binomialbetaupdateMALA <- function(X, nsites, p, beta, offset, y, failures, trials, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list) {
    .Call(`_CARBayes_binomialbetaupdateMALA`, X, nsites, p, beta, offset, y, failures, trials, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list)
}

binomialbetaupdateRW <- function(X, nsites, p, beta, offset, y, failures, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list) {
    .Call(`_CARBayes_binomialbetaupdateRW`, X, nsites, p, beta, offset, y, failures, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list)
}

binomialindepupdateMALA <- function(nsites, theta, sigma2, y, failures, trials, theta_tune, offset) {
    .Call(`_CARBayes_binomialindepupdateMALA`, nsites, theta, sigma2, y, failures, trials, theta_tune, offset)
}

binomialindepupdateRW <- function(nsites, theta, sigma2, y, failures, theta_tune, offset) {
    .Call(`_CARBayes_binomialindepupdateRW`, nsites, theta, sigma2, y, failures, theta_tune, offset)
}

poissonindepupdateMALA <- function(nsites, theta, sigma2, y, theta_tune, offset) {
    .Call(`_CARBayes_poissonindepupdateMALA`, nsites, theta, sigma2, y, theta_tune, offset)
}

poissonindepupdateRW <- function(nsites, theta, sigma2, y, theta_tune, offset) {
    .Call(`_CARBayes_poissonindepupdateRW`, nsites, theta, sigma2, y, theta_tune, offset)
}

poissonbetaupdateMALA <- function(X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list) {
    .Call(`_CARBayes_poissonbetaupdateMALA`, X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list)
}

poissonbetaupdateRW <- function(X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list) {
    .Call(`_CARBayes_poissonbetaupdateRW`, X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list)
}

poissoncarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset) {
    .Call(`_CARBayes_poissoncarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset)
}

poissoncarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset) {
    .Call(`_CARBayes_poissoncarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset)
}

zipcarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, poiind) {
    .Call(`_CARBayes_zipcarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, poiind)
}

zipcarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, poiind) {
    .Call(`_CARBayes_zipcarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, poiind)
}

zipindepupdateRW <- function(nsites, theta, sigma2, y, theta_tune, offset, poiind) {
    .Call(`_CARBayes_zipindepupdateRW`, nsites, theta, sigma2, y, theta_tune, offset, poiind)
}

zipindepupdateMALA <- function(nsites, theta, sigma2, y, theta_tune, offset, poiind) {
    .Call(`_CARBayes_zipindepupdateMALA`, nsites, theta, sigma2, y, theta_tune, offset, poiind)
}

gaussiancarupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, rho, nu2, offset) {
    .Call(`_CARBayes_gaussiancarupdate`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, rho, nu2, offset)
}

binomialmcarupdateMALA <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, trials, phioffset, denoffset, Sigmainv, rho, phi_tune) {
    .Call(`_CARBayes_binomialmcarupdateMALA`, Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, trials, phioffset, denoffset, Sigmainv, rho, phi_tune)
}

binomialmcarupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, Sigmainv, rho, phi_tune) {
    .Call(`_CARBayes_binomialmcarupdateRW`, Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, Sigmainv, rho, phi_tune)
}

poissonmcarupdateMALA <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, phioffset, denoffset, Sigmainv, rho, phi_tune) {
    .Call(`_CARBayes_poissonmcarupdateMALA`, Wtriplet, Wbegfin, nsites, nvar, phi, Y, phioffset, denoffset, Sigmainv, rho, phi_tune)
}

poissonmcarupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, phioffset, denoffset, Sigmainv, rho, phi_tune) {
    .Call(`_CARBayes_poissonmcarupdateRW`, Wtriplet, Wbegfin, nsites, nvar, phi, Y, phioffset, denoffset, Sigmainv, rho, phi_tune)
}

gaussianmcarupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, phioffset, denoffset, Sigmainv, rho, nu2, phi_tune) {
    .Call(`_CARBayes_gaussianmcarupdateRW`, Wtriplet, Wbegfin, nsites, nvar, phi, phioffset, denoffset, Sigmainv, rho, nu2, phi_tune)
}

gaussianmcarupdateMALA <- function(Wtriplet, Wbegfin, nsites, nvar, phi, phioffset, denoffset, Sigmainv, rho, nu2, phi_tune) {
    .Call(`_CARBayes_gaussianmcarupdateMALA`, Wtriplet, Wbegfin, nsites, nvar, phi, phioffset, denoffset, Sigmainv, rho, nu2, phi_tune)
}

multinomialbetaupdateRW <- function(X, nsites, J, p, col, beta, offset, y, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list, zeros) {
    .Call(`_CARBayes_multinomialbetaupdateRW`, X, nsites, J, p, col, beta, offset, y, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list, zeros)
}

multinomialmcarupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, phioffset, denoffset, Sigmainv, rho, phi_tune) {
    .Call(`_CARBayes_multinomialmcarupdateRW`, Wtriplet, Wbegfin, nsites, nvar, phi, Y, phioffset, denoffset, Sigmainv, rho, phi_tune)
}

gaussiancarmultilevelupdate <- function(Wtriplet, Wbegfin, Wtripletsum, n_individual, nsites, phi, tau2, rho, nu2, offset) {
    .Call(`_CARBayes_gaussiancarmultilevelupdate`, Wtriplet, Wbegfin, Wtripletsum, n_individual, nsites, phi, tau2, rho, nu2, offset)
}

binomialcarmultilevelupdate <- function(Wtriplet, Wbegfin, Wtripletsum, ind_area_list, n_individual, nsites, phi, tau2, y, failures, phi_tune, rho, offset) {
    .Call(`_CARBayes_binomialcarmultilevelupdate`, Wtriplet, Wbegfin, Wtripletsum, ind_area_list, n_individual, nsites, phi, tau2, y, failures, phi_tune, rho, offset)
}

poissoncarmultilevelupdate <- function(Wtriplet, Wbegfin, Wtripletsum, ind_area_list, n_individual, nsites, phi, tau2, y, phi_tune, rho, offset) {
    .Call(`_CARBayes_poissoncarmultilevelupdate`, Wtriplet, Wbegfin, Wtripletsum, ind_area_list, n_individual, nsites, phi, tau2, y, phi_tune, rho, offset)
}

poissoncarmultilevelupdateindiv <- function(ind_re_list, n_re, q, psi, sigma2, y, psi_tune, offset) {
    .Call(`_CARBayes_poissoncarmultilevelupdateindiv`, ind_re_list, n_re, q, psi, sigma2, y, psi_tune, offset)
}

binomialcarmultilevelupdateindiv <- function(ind_re_list, n_re, q, psi, sigma2, y, failures, psi_tune, offset) {
    .Call(`_CARBayes_binomialcarmultilevelupdateindiv`, ind_re_list, n_re, q, psi, sigma2, y, failures, psi_tune, offset)
}

gaussiancarmultilevelupdateindiv <- function(ind_re_list, n_re, q, psi, sigma2, nu2, offset) {
    .Call(`_CARBayes_gaussiancarmultilevelupdateindiv`, ind_re_list, n_re, q, psi, sigma2, nu2, offset)
}

